# Generated by Django 4.2 on 2023-04-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=128, verbose_name='IP地址（fqdn）')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='设备名')),
                ('vendor', models.CharField(max_length=128, verbose_name='厂商')),
                ('platform', models.CharField(max_length=128, verbose_name='平台(netmiko)')),
                ('model', models.CharField(max_length=128, verbose_name='型号')),
                ('series', models.CharField(max_length=128, verbose_name='系列')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('protocol', models.CharField(default='ssh', max_length=32, verbose_name='管理协议')),
                ('port', models.IntegerField(default=22, verbose_name='ssh端口')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
