# Generated by Django 4.2 on 2023-04-10 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=128, verbose_name='版本号')),
                ('patch', models.CharField(max_length=128, verbose_name='补丁号')),
                ('series', models.CharField(max_length=128, verbose_name='系列')),
                ('uptime', models.CharField(max_length=128, verbose_name='已运行时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dev', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cmdb.device', verbose_name='关联设备')),
            ],
        ),
    ]
