# Generated by Django 4.2 on 2023-04-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='conn_timeout',
            field=models.IntegerField(default=30, verbose_name='连接超时时间'),
        ),
        migrations.AddField(
            model_name='device',
            name='secret',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='enable密码'),
        ),
        migrations.AddField(
            model_name='device',
            name='timeout',
            field=models.IntegerField(default=30, verbose_name='CLI执行超时时间'),
        ),
    ]
