# Generated by Django 4.2 on 2023-04-15 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_device_conn_timeout_device_secret_device_timeout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='端口名')),
                ('index', models.CharField(max_length=128, verbose_name='端口索引')),
                ('phy_state', models.CharField(max_length=128, verbose_name='物理状态')),
                ('protocol_state', models.CharField(max_length=128, verbose_name='协议状态')),
                ('desc', models.CharField(blank=True, max_length=128, null=True, verbose_name='端口描述')),
                ('last_phy_uptime', models.CharField(max_length=128, verbose_name='端口上次物理up时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.device', verbose_name='关联设备')),
            ],
            options={
                'unique_together': {('dev', 'name')},
            },
        ),
    ]
