# Generated by Django 4.2 on 2023-04-15 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_interface'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=128, verbose_name='执行的命令')),
                ('config_file', models.FileField(upload_to='ConfigBackup', verbose_name='配置文件')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.device', verbose_name='关联设备')),
            ],
        ),
    ]
